
#issue here is that i configured nano to insert space instead of tabs, make it work with REAL tabs as indentation
#STRG+ALT+<tab>
default:
	g++ -std=c++17 -o leven levenshtein.cxx 
help:
	@echo "call make w/o argument"
